DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;

CREATE TABLE AUTHORS (
  id   INT PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE BOOKS (
  id   INT PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE GENRES (
  id   INT PRIMARY KEY,
  name VARCHAR(255)
);

