spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lesson14
    driverClassName: org.postgresql.Driver
    username: dalbot
    password: imagemaster
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

  thymeleaf:
    suffix: .xhtml

logging:
  level:
    org:
      hibernate:
        event:
          internal:
            DefaultPersistEventListener: TRACE
