DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;

CREATE TABLE AUTHORS (
  id   BIGSERIAL CONSTRAINT authors_pkey PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE GENRES (
  id   BIGSERIAL  CONSTRAINT genress_pkey PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE BOOKS (
  id   BIGSERIAL CONSTRAINT books_pkey PRIMARY KEY,
  name VARCHAR(255),
  author_id BIGINT NOT NULL CONSTRAINT book_authors_binding REFERENCES AUTHORS (id),
  genre_id BIGINT NOT NULL CONSTRAINT book_genre_binding REFERENCES GENRES (id)
);


