spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lesson10
    driverClassName: org.postgresql.Driver
    username: dalbot
    password: imagemaster
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false